export const GAME_CONSTANTS = {
  COSTS: {
    WORKER_FARMER: 5000,
    WORKER_RANCHER: 500,
    WORKER_MINER: 15000,
    FISHER_WORKER: 12000,
    COIN_BOOSTER: 100,
    GROWTH_BOOSTER: 50,
  },
  MULTIPLIERS: {
    GROWTH_BOOSTER: 1.5,
    COIN_BOOSTER: 2,
  },
  TIMERS: {
    FARM_TICK_RATE: 1000, // interval in ms for farm plots
  },
  FISHING: {
    WAIT_MIN_MS: 2000,
    WAIT_RANDOM_MS: 3000,
    BITE_WINDOW_MS: 1500,
    MINIGAME_MAX_TIME_MS: 6000,
    WIN_THRESHOLD: 40,
    TICK_MS: 50,
  },
  SYSTEM: {
    SEASON_TICKS_PER_DAY: 180,
    RANDOM_EVENT_CHANCE: 0.3,
  }
};
