export const GAME_CONSTANTS = {
  GRID: {
    PLOTS: 30,
    MINING_NODES: 30,
    ANIMAL_SLOTS: 36,
  },
  LEVEL: {
    XP_PER_LEVEL: 100,
    MAX_ENERGY: 200,
    MAX_ENERGY_PER_LEVEL: 10,
  },
  STARTING: {
    COINS: 100,
    ENERGY: 100,
  },
  CHANCES: {
    WORM_DROP: 0.2,
    FERTILIZER_DROP: 0.15,
    AUTO_FISHER_CATCH: 0.1,
    WATER_BOOST: 0.18,
    FISHER_TICK: 0.1,
    MINER_AUTO_TICK: 0.2,
    FEED_BONUS: 0.25,
    VARIANT_DROP: 0.05,
  },
  COSTS: {
    WORKER_FARMER: 5000,
    WORKER_RANCHER: 500,
    WORKER_MINER: 15000,
    FISHER_WORKER: 12000,
    WORKER_CHEF: 25000,
    COIN_BOOSTER: 100,
    GROWTH_BOOSTER: 50,
  },
  MULTIPLIERS: {
    GROWTH_BOOSTER: 1.5,
    COIN_BOOSTER: 2,
  },
  TIMERS: {
    FARM_TICK_RATE: 1000,
  },
  FISHING: {
    WAIT_MIN_MS: 2000,
    WAIT_RANDOM_MS: 3000,
    BITE_WINDOW_MS: 1500,
    MINIGAME_MAX_TIME_MS: 6000,
    WIN_THRESHOLD: 40,
    TICK_MS: 50,
    CATCH_EVERY_SECS: 10,
  },
  MINING: {
    REGEN_MS: { 1: 120000, 2: 90000, 3: 60000 },
    LANTERN_DURATION_MS: 300000,
    LANTERN_REGEN_MULT: 0.5,
  },
  OFFLINE: {
    MIN_SECONDS: 60,
    FISHER_CATCH_EVERY_SECS: 10,
    MINER_MINE_EVERY_SECS: 120,
  },
  SYSTEM: {
    SEASON_TICKS_PER_DAY: 180,
    RANDOM_EVENT_CHANCE: 0.3,
    TICK_INTERVAL_MS: 1000,
  },
  COMBO: {
    WINDOW_MS: 2500,
    MULTIPLIER_STEP: 0.25,
    MAX_MULTIPLIER: 4.0,
    THRESHOLD: 3,
  },
  PRESTIGE: {
    MIN_LEVEL: 25,
    MULTIPLIER_PER_COUNT: 0.1,
    MAX_MULTIPLIER: 2.0,
  },
  COLLECTION: {
    REWARD_COINS: 2500,
  },
  BREED: {
    COST: 500,
    COOLDOWN_MS: 60000,
    PRODUCE_TIME_PER_GEN: 0.95,
    MIN_PRODUCE_MULT: 0.6,
  },
  CRAFTING: {
    MAX_QUEUE_PER_TYPE: 3,
  },
  RESTAURANT: {
    MAX_TABLES: 9,
    TABLE_UPGRADE_BASE_COST: 1000,
    TABLE_UPGRADE_BESI_MULT: 2,
    TABLE_UPGRADE_BATU_MULT: 5,
    TIP_HIGH_THRESHOLD: 0.7,
    TIP_MED_THRESHOLD: 0.3,
    TIP_HIGH_MULT: 0.5,
    TIP_MED_MULT: 0.2,
    /** reputation: +TIP per point, capped */
    REP_TIP_PER_POINT: 0.002,
    REP_TIP_MAX: 0.3,
    /** reputation: spawn chance bonus, capped */
    REP_SPAWN_PER_POINT: 1 / 400,
    REP_SPAWN_MAX_BONUS: 0.5,
    /** rep gained per serve: base + patienceRatio * bonus */
    REP_SERVE_BASE: 2,
    REP_SERVE_PATIENCE_BONUS: 3,
    REP_LEAVE_PENALTY: 3,
    /** daily special dish pays this x base price */
    SPECIAL_PRICE_MULT: 1.5,
    /** golden VIP: spawn chance, price mult, patience mult */
    VIP_CHANCE: 0.07,
    VIP_PRICE_MULT: 2,
    VIP_PATIENCE_MULT: 0.7,
    /** rush hour: consecutive-serve combo */
    RUSH_STREAK: 3,
    RUSH_STREAK_WINDOW_MS: 45000,
    RUSH_DURATION_MS: 30000,
    RUSH_TIP_MULT: 2,
  },
  XP: {
    HARVEST: 10,
    MINE: 15,
    FISH: 15,
    COLLECT: 8,
    FEED_BONUS: 3,
    COOK: 0,
  },
}
